version: "3.7"

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=pedro@pmcholding.com.br"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-data:/letsencrypt"
    networks:
      - web

  postgres:
    image: pgvector/pgvector:pg16
    volumes:
      - woofed-crm-pg-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pG9x2$fK3m7zL8q#
    ports:
      - "5432:5432"
    networks:
      - internal

  redis:
    image: "redis:6.2.7-alpine"
    ports:
      - "6379:6379"
    networks:
      - internal

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:pG9x2$fK3m7zL8q#@postgres/woofed_crm_production
      REDIS_URL: redis://redis:6379/1
      MOTOR_AUTH_USERNAME="pmch"
      MOTOR_AUTH_PASSWORD="@Pmc123"
      DEFAULT_TIMEZONE=Brasilia
      ENABLE_USER_SIGNUP=true
      FRONTEND_URL: https://mycrm.pmcholding.com.br
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
      SECRET_KEY_BASE: 8a9b46892f71e7fd8739f40ce0b1af68d34f6aa47ae65276c5f351f24f36d43c2e9f3c8fc649f723d9f5671f5f9bc91d0a3d90e88a1ef9f1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`seu_dominio.com`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
    networks:
      - web
      - internal

  goodjob:
    build:
      context: .
      dockerfile: Dockerfile.goodjob
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:pG9x2$fK3m7zL8q#@postgres/woofed_crm_production
      REDIS_URL: redis://redis:6379/1
            MOTOR_AUTH_USERNAME="pmch"
      MOTOR_AUTH_PASSWORD="@Pmc123"
      DEFAULT_TIMEZONE=Brasilia
      ENABLE_USER_SIGNUP=true
      FRONTEND_URL: https://mycrm.pmcholding.com.br
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
      SECRET_KEY_BASE: 8a9b46892f71e7fd8739f40ce0b1af68d34f6aa47ae65276c5f351f24f36d43c2e9f3c8fc649f723d9f5671f5f9bc91d0a3d90e88a1ef9f1
    networks:
      - internal

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.sidekiq
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:pG9x2$fK3m7zL8q#@postgres/woofed_crm_production
      REDIS_URL: redis://redis:6379/1
            MOTOR_AUTH_USERNAME="pmch"
      MOTOR_AUTH_PASSWORD="@Pmc123"
      DEFAULT_TIMEZONE=Brasilia
      ENABLE_USER_SIGNUP=true
      FRONTEND_URL: https://mycrm.pmcholding.com.br
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
      SECRET_KEY_BASE: 8a9b46892f71e7fd8739f40ce0b1af68d34f6aa47ae65276c5f351f24f36d43c2e9f3c8fc649f723d9f5671f5f9bc91d0a3d90e88a1ef9f1
    networks:
      - internal

networks:
  web:
    external: true
  internal:
    external: false

volumes:
  woofed-crm-pg-volume:
    external: false
  traefik-data:
    external: false
